### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by lgarron** [cubing/wca-website#10]

**Comment by gagou9** [comment]
What do you mean  by accessibility ?
The ability to have our website work on old browsers ?
To be compatible with website readers for blind people ?
To have a "no-mouse" compatible website ?

I was looking for an issue to talk about no JS fallback, but it may not be the right place.

I definitely don't like the fact that we rely on javascript !
It involves way more bandwidth usage, more resources on the client, and is never really working the same way on all browser (this last statement may be wrong today I guess)

**Comment by FatBoyXPC** [comment]
There's actually a lot of misinformation here, but I'll put that aside for
now.

The beauty of CCM is that it's *not* going to be the main WCA system, at
least, I don't think. There's too much chatter about splitting it up. Point
is: WCA doesn't rely on JS currently, and it won't at least for awhile. If
you want to use CCM and don't have js enabled, then that's on you. All 5
major browsers (and we can throw in mobile ones, too) have js enabled by
default. I think we are fine here.

On the same note: Cubecomps uses a fair bit of js, so if you can use it, no
reason you can't use CCM.

**Comment by pochmann** [comment]
On Feb 4, 2015 7:46 PM, "Gaël Dusser" <notifications@github.com> wrote:
>
>   javascript !
> It involves way more bandwidth usage

How so? I think it involves *less*.

**Comment by gagou9** [comment]
Hm I meant the actual WCA website doesn't work without JS enabled, that's the point.
(but it works with w3m, and that's weird 'cause it then should work with FF with JS disabled then!!)

**Comment by gagou9** [comment]
@pochmann oh really ?
So why some webmails have this fallback no-js for slow connexions then? (and it actually is really more reactive when using slow co)

**Comment by gagou9** [comment]
@FatBoyXPC could you correct me regarding my misinformations ?

**Comment by gagou9** [comment]
And that's not "on me", that's on a lot of people using really bad connections, very old computers, internet cafes, or whatever reason that makes using JS a pain in the ass.

**Comment by jbcm627** [comment]
For the WCA website, I think we do need a non-js version (for accessibility and SEO), at least for non administrative pages.  CCM is different; I don't think a fallback is necessary there.

**Comment by FatBoyXPC** [comment]
So the bandwidth usage directly correlates to how many page (re)loads you
do when you're on the site. In a normal HTTP request, you download all of
the headers along with the full HTML markup. With meteor, you download the
bulk of the app on the initial load. When you navigate to a new page in a
meteor app, you only download the pertinent data. Meteor is (self
proclaimed) data over the wire only, which means no markup. I'm not
entirely sure when new templates get loaded. As in, I'm not sure if all the
templates get loaded on initial page load, or if they get loaded as you
navigate to them.

At any rate - going through every single page in a meteor app, then every
single page in a typical app, you'll most certainly use less bandwidth with
meteor. When you have a row of table output in a normal app, you get all of
that markup *for every row. *When you have a meteor app, a row is going to
correspond with a template. You download this template once. The client
side javascript will iterate over it and add it to the table appropriately.

So, about bandwith concerns: You're right if you compare somebody visiting
one or two pages then leaving the site, but there is most definitely a
point in which the tables turn. If the other concern is "Well that's just a
*lot* of javascript!", well, minification goes a long way.

More resources on the client: While technically true, it's irrelevant even
on 5+ year old hardware. I'm fully aware there are older computers than
that out there, but I know that a machine I built 6+ years ago can run this
time, and if I still had my 11 year old machine still put together, I would
to test it just to see. My point is: If your'e on winxp+, or mac/linux
equivalentsof age, and you're on a modern browser - I don't see resources
being an issue.

(this last statement may be wrong today I guess) - Absolutely. Javascript's
only inconsistencies lie with IE vs all the others (for the most part).
Even so, Microsoft has gone a long way at remedying this, as they finally
realize they aren't (and haven't been) the dominant browser. Yes, there are
still CSS inconsistencies amonst some browsers (again, mostly IE vs the
rest), but we aren't even talking about CSS here anyways :)

And that's not "on me" - To my knowledge, CCM will not be forced upon
competition managers by the WCA. That being said, means it is entirely your
choice. Therefore, yes, it *is* on you. If you don't meet the
qualifications, you don't have a right to be upset when this *free* software
won't work for you. Ultimately, nobody has a right to bet upset when free
software doesn't work for them.

people using really bad connections - Awesome point! It's a good thing that
Meteor stores everything in local storage if it loses connection with the
server, and keeps it in there until it reconnects! This honestly might be
one of the weakest points, as meteor has handled this quite nicely.

whatever reason that makes using JS a pain in the ass - This isn't the
early 2000s anymore. JS is no longer a pain in the ass, it's definitely the
way of the future!

**Comment by gagou9** [comment]
thanks for all these clarifications.

let me say that I'm not upset :) plus I really appreciate all that work being done, as well as how featureful CCM is (going to be) !!

I just wanted to point out that it is not going to be working everywhere, and that devs should think about non-compatible clients.
And I was talking about the website, not CCM, as I really understand they are different things and CCM is not gonna be the most visible part of the WCA softwares project.

So the thing I probably didn't understand is that meteor is not gonna be used for the public website, is it ?

The explanation about bandwidth is very clear, thanks. The thing is that, if it does like, say gmail, like downloading everything on the client and then display a browsable page, then it's never gonna work on slow connections. (i was very rarely able to load gmail or heavy JS loaders in china, neither in morocco and definitely in other places as well). Of course, when it's loaded, it works. 
This remark doesn't count if there is no plan on moving the public website to meteor, but is also valid for resources : 10+ years old computers are very common, at least I know *a lot* of people using old computers. With linux (debian mostly, or tails, or linux mint) and firefox. Firefox is a modern browser, but has a very hard time when working with a lot of JS. The thing I just realise is that loading page with ajax isn't really what I will call "a lot of JS", and meteor may not eat as much resources as 0bin or gmail do, for example.


thanks!

**Comment by FatBoyXPC** [comment]
You are half and half correct about meteor on the public website. The way I
interpret the other email thread, is that CCM is going to handle all things
management related, and the rest of the site will be driven via small
dynamic scripts to pull content from the db. I'm an advocate of these two
projects sharing the database, but we'll see. This would make importing
results so seamless.

**Comment by jbcm627** [comment]
Accessibility is good to keep in mind, and discussion is good, but I'm not sure this issue is actionable. As such I am closing this.

If there are any specific issues to address, this can be re-opened, or another issue made.

**Comment by lgarron** [comment]
By accessibility I meant [accessibility](https://en.wikipedia.org/wiki/Accessibility), not performance or availability.

**Comment by jbcm627** [comment]
There is still nothing actionable in this issue. What specific issues are there that need to be fixed?

**Comment by lgarron** [comment]
Some examples using [Accessibility Developer Tools](https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb?hl=en):
![screen shot 2015-04-29 at 14 01 56](https://cloud.githubusercontent.com/assets/248078/7401462/214805de-ee79-11e4-95cb-42829f52eaf5.png)

Keyboarding through our menu is actually pretty okay.
Haven't really had time to test with our screen reader.

I don't mind closing this particular issue, but we should at least have it written down somewhere as something to explicitly keep in mind for any parts of the site we rewrite.

**Comment by jfly** [comment]
As a general rule, I'm with Jim: I prefer tons of tiny issues to meta issues. That said, there isn't a huge cost to having an open issue about this, and if it reminds us to get back to this, that's a plus.

**Comment by jfly** [comment]
Lets continue discussion over at https://github.com/cubing/worldcubeassociation.org/issues/50.
