### ISSUE TITLE
Contact forms / listings

### ISSUE THREAD

**Issue by jbcm627** [cubing/wca-website#15]
Right now the wca-website list receives a lot of emails not relevant to the website itself.  It would be good to think about how to make a contact form or page that more strongly suggests people send to the appropriate list.

I would like to provide both emails and contact forms for all teams, but the emails really should be behind a captcha or something.

Maybe something like a multi-step form, where the first step is to pick a category... then an actual contact form + email as the next step.

**Comment by lgarron** [comment]
Also, we really need to have a page that answers competition requests.

**Comment by gagou9** [comment]
Also we could have some kind of "public questions and answer", which could be more usefull and would avoid us getting emails asking many times the same question :)
https://github.com/cubing/wca-website/issues/12#issuecomment-86892723

But I don't know whether this is actually a thing you like.

**Comment by jfly** [comment]
I don't know much about quora or stackoverflow, but could one of those websites be a good place to put this? I know it would mean us not controlling the data, but it would save us the hassle of maintaining the code.

**Comment by jfly** [comment]
Closing this issue. Please reopen over at https://github.com/cubing/worldcubeassociation.org if interested. I think this might make more sense to revisit once we store the structure of the WCA in our database (knowing who delegates are, etc)
