### ISSUE TITLE
Replacement for Drupal Features

### ISSUE THREAD

**Issue by jbcm627** [cubing/wca-website#16]
I'd like this to replace all of the features currently used in Drupal (which isn't a very long list).  Something along the lines of:

 - Non-developers should be able to create and edit a couple semantically and functionally different types of content, along the lines of "announcements" and "pages".

 - Provide a feed (the front page itself doesn't need to be a feed).

 - Provide contact information / forms

 - Consider putting organizational information in the database, like lists of delegates or team members.

Unless keeping Drupal seems like a good idea.

**Comment by jfly** [comment]
Drupal also gives us a fancy 404 page. We could potentially replace it with google site search.

**Comment by jfly** [comment]
I talked to Jim about this, and here's our current thinking:

- Use static md committed to github for everything other than posts/*. This includes https://www.worldcubeassociation.org/contact, which will become dynamically generated once we've put the concept of teams into our db. Until we do so, we will obsfucate emails with js.
- For all stuff in posts/*, we will have our own "posts" table. Jim will be able to help migrate stuff from the drupal schema into whatever schema we choose. We'll also need to provide an RSS feed, and some sort of editing capability (which will require user accounts).

**Comment by lgarron** [comment]
For MVP, why can't we us `.md` files for posts?

**Comment by jbcm627** [comment]
I don't think we want thousands of posts stored in a filesystem, and I'm not sure that we care about revisions.  One idea was just to add text columns to the competitions table.

**Comment by jfly** [comment]
I actually wouldn't mind thousands of files, but I do want the results posting flow to be smooth, even in a minimum viable product. Committing files to github every time we post results doesn't feel right to me.

**Comment by jfly** [comment]
This has been done over at [WcaOnRails](https://github.com/cubing/worldcubeassociation.org/tree/master/WcaOnRails)
