### ISSUE TITLE
Home page has old favicon.

### ISSUE THREAD

**Issue by lgarron** [cubing/wca-website#17]
https://www.worldcubeassociation.org/ has the old, terrible favicon.

See https://www.worldcubeassociation.org/results/ for the slightly less terrible favicon in action.

**Comment by lgarron** [comment]
Jeremy, could you see if this is due to the server rearrangement/is easy to fix?

**Comment by jfly** [comment]
Taking a look now. Do you know that this is a regression?

**Comment by lgarron** [comment]
Yep, definitely a regression.

**Comment by lgarron** [comment]
It seems Drupal has reverted to https://www.worldcubeassociation.org/files/garland_favicon_0.ico

**Comment by jfly** [comment]
I ran the following command on the server `cubing@james-smith:~/worldcubeassociation.org/drupal/files$ cp ../../results/images/wca.ico wca.ico`, and changed the favicon to "wca.ico" via https://www.worldcubeassociation.org/admin/appearance/settings/wca_drupal_bootstrap.

**Comment by lgarron** [comment]
Looks fixed now. Thanks! :-)
