### ISSUE TITLE
New Results System

### ISSUE THREAD

**Issue by lgarron** [cubing/wca-website#2]
I don't plan for this to be the initial priority of the redesign (#1), but it would be nice to redo everything at once.

In particular, I think we should move the new system if at all possible, by focusing on everything that's actually needed. In particular, I think we should be okay with throwing out statistics in order to get things running. The world won't end if they're gone for a few months. (And people like them enough that they'll probably get re-implemented soon if we do things right.)

**Comment by jbcm627** [comment]
Closing this issue; see the [cubing/worldcubeassociation.org](https://github.com/cubing/worldcubeassociation.org) repo.
