### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by jfly** [cubing/wca-website#22]
See email thread here https://groups.google.com/d/msg/wca-software/dX1Enl1Iy0U/7ohRaCqCYGUJ.

**Comment by jfly** [comment]
Just stumbled across this: http://s3tools.org/s3cmd

**Comment by gagou9** [comment]
You guessed what I think of Amazon S3, especially when we have at least 2 other free options :)
I can think of a rsync running with Lucas' server, as well as one with one of my servers.

I don't think we should pay anything...

**Comment by jfly** [comment]
I'd also like to use S3 for image uploads, so there's that.

I don't think S3 is very expensive, and it gives us redundancy that backing up to 1 or 2 machines just wouldn't give us. If we do our own home spun thing, we'll have to manage credentials, which I'm not wild about.

I don't want to let the perfect get in the way of the good here, though. All I know right now is that I want to use S3 for image uploads.

**Comment by pochmann** [comment]
S3 is good. Tarsnap uses it well. It's almost free. You make no sense.

**Comment by lgarron** [comment]
I think we're agreed that S3 is reliable, quite cheap, and has good tools for (encrypted) backups. How about we plan to use it, and then @gagou9 can offer an additional server if he wants?

**Comment by gagou9** [comment]
I understand your arguments, and I wouldn't and couldn't "block" your decision.
But of course, what I don't like with Amazon is that it's once again a huge company that goes the opposite way of the net neutrality and centralises data and treats employees very bad and so on. In my whole life I try to avoid things which are totaly in the opposite of my way of thinking, and I hate amazon as I hate Google and Dropbox and all these shit.
But that's okay I can also be an easy person and accept the collective choice!
