### ISSUE TITLE
Things we actually need

### ISSUE THREAD

**Issue by lgarron** [cubing/wca-website#4]
In contrast to #3. Anything that isn't extremely obvious should go here.

- [ ] DOCUMENTATION.
  - Ideally, there should be little to document. Whatever. The README for any given part of the project should  just make it clear how to get things running, so that you can figure out the rest.
-  [ ] Results admin interface
  - Includes a bunch of check scripts and stuff in PHP.
-  [ ] Some way to edit pages. **Doesn't have to be a CMS.**
  - While something like Drupal is nice in theory, in practice very few people ever make changes to the website. These are all people who can handle something more raw than a fancy-schmancy CMS.
-  [ ] Trivial dev setup.
  - No Rails, no `node.js`, no SASS/LESS, no libraries we don't need.
  - Minimal database setup.
-  [ ] Sane URLs

**Comment by jbcm627** [comment]
Closing this issue as well. Refer to the [cubing/worldcubeassociation.org](https://github.com/cubing/worldcubeassociation.org) repo (or other issues here) for specific discussions / developments.
