### ISSUE TITLE
Site Structure

### ISSUE THREAD

**Issue by lgarron** [cubing/wca-website#5]
Here's a list of every page on the WCA website I know of (condensing some dynamic sections and admin stuff in certain sub-paths).

I want as much of this as possible (within reason) to be accessible from the front page. Else, two clicks via the menu.
Labelings are how the pages *currently* served. I'd love to unify some things. Ultimately, that's not as important as getting things to work, though.

Note: There are no subdomains. This helps with maintenance, portability, and HTTPS.

## Drupal

- [`/`](https://www.worldcubeassociation.org/)
- [`/node`](https://www.worldcubeassociation.org/node) ("actual" location of competition announcement feed)
- [`/about`](https://www.worldcubeassociation.org/about)
- [`/delegates`](https://www.worldcubeassociation.org/delegates)
- [`/organisations`](https://www.worldcubeassociation.org/organisations)
- [`/contact`](https://www.worldcubeassociation.org/contact)
- [`/logo`](https://www.worldcubeassociation.org/logo)
- [`/score-tools`](https://www.worldcubeassociation.org/score-tools)
- [`/regulations/announcements`](https://www.worldcubeassociation.org/regulations/announcements) (see below)

### Requires Login (via [`/user`](https://www.worldcubeassociation.org/user))

- [`/admin`](https://www.worldcubeassociation.org/admin)

## Results System (PHP)

- [`/admin`](https://www.worldcubeassociation.org/admin)
- [`/results`](https://www.worldcubeassociation.org/results)
- [`/results/events.php`](https://www.worldcubeassociation.org/results/events.php) ("Rankings")
- [`/results/regions.php`](https://www.worldcubeassociation.org/results/regions.php) ("Records")
- [`/results/competitions.php`](https://www.worldcubeassociation.org/results/competitions.php)
- [`/results/persons.php`](https://www.worldcubeassociation.org/results/persons.php)
  - [`/results/person_set.php`](https://www.worldcubeassociation.org/results/person_set.php) (Image Submission)
- [`/results/media.php`](https://www.worldcubeassociation.org/results/media.php)
  - [`/results/media_insertion.php`](https://www.worldcubeassociation.org/results/media_insertion.php)
- [`/results/statistics.php`](https://www.worldcubeassociation.org/results/statistics.php)
- [`/results/misc.php`](https://www.worldcubeassociation.org/results/misc.php)
  - Various long-form statistics.
  - [`/results/misc/export.html`](https://www.worldcubeassociation.org/results/misc/export.html)

Note the "Rankings" and "Records" pages have been renamed, without a URL change.

### Requires Login

- [`/results/admin/`](https://www.worldcubeassociation.org/results/admin/)

## Regulations

- [`/regulations`](https://www.worldcubeassociation.org/regulations)
- [`/regulations/wca-regulations-and-guidelines.pdf`](https://www.worldcubeassociation.org/regulations/wca-regulations-and-guidelines.pdf) (PDF)
- [`/regulations/guidelines.html`](https://www.worldcubeassociation.org/regulations/guidelines.html)
- [`/regulations/scrambles/`](https://www.worldcubeassociation.org/regulations/scrambles/)
- [`/regulations/history/`](https://www.worldcubeassociation.org/regulations/history/)
  - Old Regulations
  - Old changelogs
- [`/regulations/translations/`](https://www.worldcubeassociation.org/regulations/translations/)
  - Translations within subdirectories (contains Regulations, Guidelines, PDF, and CSS+logo)
- [`/regulations/announcements`](https://www.worldcubeassociation.org/regulations/announcements) (currently served from **Drupal**)

## Forum (phpBB)

- [`/forum`](https://www.worldcubeassociation.org/forum)

## API (Python)

- [`/api/`](https://www.worldcubeassociation.org/api/) ([source](https://github.com/cubing/wca-website/tree/api))

**Comment by jfly** [comment]
I moved all the not out of date information from this issue over to https://github.com/cubing/worldcubeassociation.org/wiki/The-state-of-worldcubeassociation.org. Closing this issue.
