### ISSUE TITLE
Send HSTS header on all pages

### ISSUE THREAD

**Issue by lgarron** [cubing/wca-website#6]
Right now, it's only being served from Drupal. This is probably enough to cover most users, but we can do better.

Should be as easy as copying the relevant section from the Drupal `.htaccess` file into all the mapped directories ([see the "Remappings" section in the  private wca-website-php wiki](https://github.com/cubing/wca-website-php/wiki/Full-Setup#remappings)).

**Comment by jbcm627** [comment]
This should now be done, via https://github.com/cubing/worldcubeassociation.org/blob/master/webroot/.htaccess
