### ISSUE TITLE
HTTPS Everywhere

### ISSUE THREAD

**Issue by lgarron** [cubing/wca-website#7]
Might as well. <https://www.eff.org/https-everywhere/rulesets>

--------

Low priority for now, since:
- we redirect to SSL immediately
- Google results and many links are now directly to HTTPS
- we, uh, should be using HSTS (#6)

**Comment by jbcm627** [comment]
I'm not familiar with the browser plugin. We should be redirecting to SSL everywhere. If this is worth pursuing, please re-open (particularly over at cubing/worldcubeassociation.org).
