### ISSUE TITLE
New Theme TODOs

### ISSUE THREAD

**Issue by lgarron** [cubing/wca-website#8]
##  Navigation Stuff

- [ ] Breadcrumbs or titles everywhere / highlight menu items of current page.
- [x] Better site-wide logo (thin dark gray border instead of shadow
- [ ] icons for sections (see <http://cubingchina.com>)
- [x] Fallback in case JS isn't working.
  - [ ] Make sure all the fallback pages have all the relevant links.

## Drupal

- [x] Theme Drupal
- [ ] Front page with interesting/relevant stuff.
- [x] Restore misc. small parts
  - [x] RSS link?
- [x] Restore borders around sticky posts.

## Forum

- [ ] Theme the forum

## Results

- [ ] Theme results pages
- [ ] More responsive tables?
- [ ] Titles on results pages
- [ ] Fix/uncomment suppressed deprecation warnings:
  - [ ] `mysql_connect`
  - [ ] `processLinks` in `_links.php`
- [ ] Style database export

## Regulations

- [ ] Link to other Regs stuff from top regs page
- [ ] Make all translations easier to find.
- [ ] Links to Guidelines for translations
- [ ] Make new Regulations pages? (e.g. page about puzzles)
- [ ] Link to a WCA-hosted version of jQuery (find out what's causing [this page](https://www.worldcubeassociation.org/regulations/assets/jquery.min.js) to redirect while all the other assets work?)
- [ ] Fix `active` menu highlighting of WRC announcements (should be under Regulations, not Information)

**Comment by jfly** [comment]
I'm closing issues on wca-website. Please reopen over at https://github.com/cubing/worldcubeassociation.org/ if this is still relevant.
