### ISSUE TITLE
Competition Information

### ISSUE THREAD

**Issue by lgarron** [cubing/wca-website#9]
Right now, the results system pretty much assumes you already know how competitions work. I want to add a new section for information about competitions, including:

- Upcoming competitions (maybe someday we can have "competitions near you" like cubingusa.com, but the filtering options on the [competitions pages](https://www.worldcubeassociation.org/results/competitions.php) are okay for now.
- Tutorials/references for new competitors.
  - There have been a lot of unofficial ones, and I think it's time to unify these efforts.
  - This might be the place to put [simplified Regulations](https://github.com/cubing/wca-documents/issues/69).
- Some details about the history of the WCA and how it currently operates. (The current Drupal pages skirt around this.)

@larf: Any interest/comments?

**Comment by lgarron** [comment]
I think we should also have a page about how competitions are organized, and how to contact Delegates about the possibility of holding one in your region.

Competition requests get posted on forums and WCA contact forms all the time.

**Comment by jbcm627** [comment]
If Bryan is OK with it, I wouldn't mind moving CubingUSA's guide to the WCA website:
http://www.cubingusa.com/cguide.php

**Comment by Alukret** [comment]
Dear WCA Website Team,

I don't know what is the reason, but for about 4 days we can't edit
competitors' list of Ukrainian Open 2015:
https://www.worldcubeassociation.org/results/competition_edit.php?competitionId=UkrainianOpen2015&password=00d7512c9d53fa7f90c7c944c71a1d536aa11b1d&rand=102531099
Can you explain what is happened?

Best regards,
Roman Ostapenko

**Comment by SAuroux** [comment]
Hi Roman,

you just posted your confidential admin link for the competition management
page on a public mailing list. Don#t do that again in the future, unless
you want random people in the world messing with your registration
information. ;)

I just resetted the password and will mail you the new URL seperately.

Have fun,

Sébastien

2015-05-24 23:14 GMT+02:00 Alukret <notifications@github.com>:
